language: python
python:
- '2.7'
cache: pip
install:
- pip install -r requirements.txt
script: pytest
deploy:
  api_key:
    secure: kcopF0/d6MHAFj9oiDLHwmsse4hEOKtnTEcsztL3PBDM7d6bXcKadpzS72b3JC/w5Zb7/1DMBR88J8fmEIP4JIx+3Xntm0lEzMUBhrtDJihSps+v4X2qZQk4tyUELGXYitQ3OZDQvn2OENxDWc2GUxwofqzCzi7p0ZxX8Ps9ljo2Y/cz9rb+63CwtR+sfvZA1wTKcDWC6kmh8h7KNUa8oIgxoX5sp5j3jrlUryalVQjToGIO1kkrUSI35HiqfWbjLE2AgQBtxchMAfVC44HoVroI3RPJKF98/oEcVh1eIrivWA6uculIR41W5eWgrD3SkWCclWzzBJQaLSB2Wjps0eT/eRWcRZ/dfu7QHzFJ6fns4miuawGI5cHMmW38wrVvyDULs2plnteG/O2M/xZMzkZcaV8AtDC1BhxlCb54sX26lCicceHY6i6J7u5mo2YDqXRojXko7LMkpWpwnzA/hfLN4xGZBNcU9368IAzP+nexLnRR6I7J64/FAzobF34VBpEJ3QyXFe3EsW5fItfYPq8a2/CvBahvHodhmhcWI/UHx6aTHKRaraz2+l7dMJ69WzfiFiENmPkpqD3pVn4PDFUya2JwimMyRQNz+k5FL1vTkxVj7nHRMp6KePwZJSHiam+9RKnHkMuDq5EMxIuCBXk5e+arIZpRpFh8N6g6yKQ=
